# 1. tag local
# 2. push tag to github
# 3. npm publish
# 4. sync tag -> release, add changelog

name: auto-publish

permissions:
  id-token: write # Required for OIDC
  contents: write

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      # install deps
      - run: pnpm install --frozen-lockfile

      - name: npm publish
        run: npm publish --access public

      - run: pnpx changeloggithub@0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: pnpx npm-sync-taobao needle-kit
